apiVersion: v1
kind: Service
metadata:
  name: aiapub-service
  labels:
    app: aiapub
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30010
  selector:
    app: aiapub
    
  #externalIPs:
  #  - 80.11.12.10
