apiVersion: v1
kind: Service
metadata:
  name: aiapub-service
  labels:
    app: aiapub
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 38888
  selector:
    app: aiapub
    
  #externalIPs:
  #  - 80.11.12.10
